channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asciitree=0.3.3
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cfitsio=3.470
  - charls=2.2.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - fasteners=0.16.3
  - giflib=5.2.1
  - imagecodecs=2021.8.26
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.4.0
  - jedi=0.18.1
  - jgo=1.0.4
  - jpeg=9e
  - jupyter_client=7.3.5
  - jupyter_core=4.11.1
  - jxrlib=1.1
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.85.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzopfli=1.0.3
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.6
  - maven=3.8.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msgpack-python=1.0.3
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - numcodecs=0.9.1
  - numpy=1.23.3
  - numpy-base=1.23.3
  - openjdk=8.0.332
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - packaging=21.3
  - paintera=0.26.0
  - paintera-conversion-helper=0.10.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - pyparsing=3.0.9
  - python=3.9.13
  - python-dateutil=2.8.2
  - pyzmq=23.2.0
  - readline=8.2
  - setuptools=65.5.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.39.3
  - stack_data=0.2.0
  - tifffile=2021.7.2
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.1.1
  - tzdata=2022f
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.6
  - zarr=2.8.1
  - zeromq=4.3.4
  - zfp=0.5.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - contourpy==1.0.7
      - cycler==0.11.0
      - cython==3.0.5
      - daisy==1.0
      - dnspython==2.4.2
      - fastremap==1.13.3
      - fill-voids==2.0.3
      - fonttools==4.38.0
      - funlib-geometry==0.2
      - funlib-math==0.1
      - funlib-persistence==0.1.0
      - funlib.segment @ git+https://github.com/funkelab/funlib.segment@b2d5c6c84433383143242383c6ec04d386095ae0
      - h5py==3.10.0
      - imageio==2.26.1
      - kiwisolver==1.4.4
      - lazy-loader==0.2
      - matplotlib==3.6.3
      - networkx==3.0
      - pillow==9.4.0
      - pymongo==4.5.0
      - pywavelets==1.4.1
      - scikit-image==0.20.0
      - scipy==1.9.1
      - tqdm==4.66.1